# Generated by Django 5.1.2 on 2024-10-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerente del proyecto",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Miembros del equipo",
            ),
        ),
    ]
