# Generated by Django 5.1.2 on 2024-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "Por hacer"),
                            ("IN_PROGRESS", "En progreso"),
                            ("REVIEW", "En revisión"),
                            ("DONE", "Completada"),
                        ],
                        default="TODO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha límite")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-created_at"],
            },
        ),
    ]
